// Auto-generated by StatAndIntrinsicEnumGenerator.cs on 6/4/2025 5:09:42 PM
// Based on IntrinsicSchemaObject assets found in StatSettings.
// Total items found: 12

using System;

namespace _src.Scripts.StatsHelpers.StatsHelpers.Data
{
    public enum EIntrinsic : byte
    {
        NullIntrinsic = 0, // From: Null Intrinsic, GUID Prefix: 5852
        Weight = 1, // From: 1 Weight, GUID Prefix: 4da0
        Money = 2, // From: 2 Money, GUID Prefix: b0f6
        XP = 3, // From: 3 XP, GUID Prefix: a3b2
        DistanceRun = 4, // From: 4 Distance Run, GUID Prefix: f7bd
        RunningTime = 5, // From: 5 Running Time, GUID Prefix: ef98
        JumpsPerformed = 6, // From: 6 Jumps Performed, GUID Prefix: cb70
        SlidesPerformed = 7, // From: 7 Slides Performed, GUID Prefix: 8db4
        NearMisses = 8, // From: 8 Near Misses, GUID Prefix: 3686
        PowerupsCollected = 9, // From: 9 Powerups Collected, GUID Prefix: 20b2
        DetectedCount = 10, // From: 10 Detected Count, GUID Prefix: 5320
        MetroCoin = 12, // From: 12 Metro Coin, GUID Prefix: d396
    }

    public static class EIntrinsicExt
    {
        public static string GetGuid(this EIntrinsic item)
        {
            return item switch
            {
                EIntrinsic.NullIntrinsic => "5852",
                EIntrinsic.Weight => "4da0",
                EIntrinsic.Money => "b0f6",
                EIntrinsic.XP => "a3b2",
                EIntrinsic.DistanceRun => "f7bd",
                EIntrinsic.RunningTime => "ef98",
                EIntrinsic.JumpsPerformed => "cb70",
                EIntrinsic.SlidesPerformed => "8db4",
                EIntrinsic.NearMisses => "3686",
                EIntrinsic.PowerupsCollected => "20b2",
                EIntrinsic.DetectedCount => "5320",
                EIntrinsic.MetroCoin => "d396",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, "Unknown EIntrinsic value for GetGuid.")
            };
        }

        public static string ToName(this EIntrinsic item)
        {
            return item switch
            {
                EIntrinsic.NullIntrinsic => "Null Intrinsic",
                EIntrinsic.Weight => "Weight",
                EIntrinsic.Money => "Money",
                EIntrinsic.XP => "XP",
                EIntrinsic.DistanceRun => "Distance Run",
                EIntrinsic.RunningTime => "Running Time",
                EIntrinsic.JumpsPerformed => "Jumps Performed",
                EIntrinsic.SlidesPerformed => "Slides Performed",
                EIntrinsic.NearMisses => "Near Misses",
                EIntrinsic.PowerupsCollected => "Powerups Collected",
                EIntrinsic.DetectedCount => "Detected Count",
                EIntrinsic.MetroCoin => "Metro Coin",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, "Unknown EIntrinsic value for ToName.")
            };
        }

        public static EIntrinsic FromGuid(string guid4)
        {
            if (guid4 == null || guid4.Length != 4)
            {
                throw new ArgumentException($"GUID must be 4 characters long.", nameof(guid4));
            }

            return guid4 switch
            {
                "5852" => EIntrinsic.NullIntrinsic,
                "4da0" => EIntrinsic.Weight,
                "b0f6" => EIntrinsic.Money,
                "a3b2" => EIntrinsic.XP,
                "f7bd" => EIntrinsic.DistanceRun,
                "ef98" => EIntrinsic.RunningTime,
                "cb70" => EIntrinsic.JumpsPerformed,
                "8db4" => EIntrinsic.SlidesPerformed,
                "3686" => EIntrinsic.NearMisses,
                "20b2" => EIntrinsic.PowerupsCollected,
                "5320" => EIntrinsic.DetectedCount,
                "d396" => EIntrinsic.MetroCoin,
                _ => throw new ArgumentOutOfRangeException(nameof(guid4), guid4, "Unknown GUID for EIntrinsic.")
            };
        }
    }
}