// Auto-generated by StatAndIntrinsicEnumGenerator.cs on 6/15/2025 5:06:39 AM
// Based on IntrinsicSchemaObject assets found in StatSettings.
// Total items found: 19

using System;

namespace _src.Scripts.StatsHelpers.StatsHelpers.Data
{
    public enum EIntrinsic : byte
    {
        NullIntrinsic = 0, // From: Null Intrinsic, GUID Prefix: 5852
        Weight = 1, // From: 1 Weight, GUID Prefix: 4da0
        Money = 2, // From: 2 Money, GUID Prefix: b0f6
        XP = 3, // From: 3 XP, GUID Prefix: a3b2
        Stamina = 4, // From: 4 Stamina, GUID Prefix: f7bd
        ForwardSpeed = 5, // From: 5 Forward Speed, GUID Prefix: ef98
        JumpForce = 6, // From: 6 Jump Force, GUID Prefix: cb70
        JumpPerformed = 7, // From: 7 Jump Performed, GUID Prefix: 8db4
        NearMisses = 8, // From: 8 Near Misses, GUID Prefix: 3686
        PowerupsCollected = 9, // From: 9 Powerups Collected, GUID Prefix: 20b2
        DetectedCount = 10, // From: 10 Detected Count, GUID Prefix: 5320
        CurrentThreats = 11, // From: 11 Current Threats, GUID Prefix: 4af8
        MetroCoin = 12, // From: 12 Metro Coin, GUID Prefix: d396
        Health = 13, // From: 13 Health, GUID Prefix: bfe6
        LineSwitchSpeed = 14, // From: 14 Line Switch Speed, GUID Prefix: c3a5
        HidePerfromed = 15, // From: 15 Hide Perfromed, GUID Prefix: eef8
        SlidePerfromed = 16, // From: 16 Slide Perfromed, GUID Prefix: e84e
        LineSwitched = 17, // From: 17 Line Switched, GUID Prefix: df05
        Height = 18, // From: 18 Height, GUID Prefix: 0519
    }

    public static class EIntrinsicExt
    {
        public static string GetGuid(this EIntrinsic item)
        {
            return item switch
            {
                EIntrinsic.NullIntrinsic => "5852",
                EIntrinsic.Weight => "4da0",
                EIntrinsic.Money => "b0f6",
                EIntrinsic.XP => "a3b2",
                EIntrinsic.Stamina => "f7bd",
                EIntrinsic.ForwardSpeed => "ef98",
                EIntrinsic.JumpForce => "cb70",
                EIntrinsic.JumpPerformed => "8db4",
                EIntrinsic.NearMisses => "3686",
                EIntrinsic.PowerupsCollected => "20b2",
                EIntrinsic.DetectedCount => "5320",
                EIntrinsic.CurrentThreats => "4af8",
                EIntrinsic.MetroCoin => "d396",
                EIntrinsic.Health => "bfe6",
                EIntrinsic.LineSwitchSpeed => "c3a5",
                EIntrinsic.HidePerfromed => "eef8",
                EIntrinsic.SlidePerfromed => "e84e",
                EIntrinsic.LineSwitched => "df05",
                EIntrinsic.Height => "0519",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, "Unknown EIntrinsic value for GetGuid.")
            };
        }

        public static string ToName(this EIntrinsic item)
        {
            return item switch
            {
                EIntrinsic.NullIntrinsic => "Null Intrinsic",
                EIntrinsic.Weight => "Weight",
                EIntrinsic.Money => "Money",
                EIntrinsic.XP => "XP",
                EIntrinsic.Stamina => "Stamina",
                EIntrinsic.ForwardSpeed => "Forward Speed",
                EIntrinsic.JumpForce => "Jump Force",
                EIntrinsic.JumpPerformed => "Jump Performed",
                EIntrinsic.NearMisses => "Near Misses",
                EIntrinsic.PowerupsCollected => "Powerups Collected",
                EIntrinsic.DetectedCount => "Detected Count",
                EIntrinsic.CurrentThreats => "Current Threats",
                EIntrinsic.MetroCoin => "Metro Coin",
                EIntrinsic.Health => "Health",
                EIntrinsic.LineSwitchSpeed => "Line Switch Speed",
                EIntrinsic.HidePerfromed => "Hide Perfromed",
                EIntrinsic.SlidePerfromed => "Slide Perfromed",
                EIntrinsic.LineSwitched => "Line Switched",
                EIntrinsic.Height => "Height",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, "Unknown EIntrinsic value for ToName.")
            };
        }

        public static EIntrinsic FromGuid(string guid4)
        {
            if (guid4 == null || guid4.Length != 4)
            {
                throw new ArgumentException($"GUID must be 4 characters long.", nameof(guid4));
            }

            return guid4 switch
            {
                "5852" => EIntrinsic.NullIntrinsic,
                "4da0" => EIntrinsic.Weight,
                "b0f6" => EIntrinsic.Money,
                "a3b2" => EIntrinsic.XP,
                "f7bd" => EIntrinsic.Stamina,
                "ef98" => EIntrinsic.ForwardSpeed,
                "cb70" => EIntrinsic.JumpForce,
                "8db4" => EIntrinsic.JumpPerformed,
                "3686" => EIntrinsic.NearMisses,
                "20b2" => EIntrinsic.PowerupsCollected,
                "5320" => EIntrinsic.DetectedCount,
                "4af8" => EIntrinsic.CurrentThreats,
                "d396" => EIntrinsic.MetroCoin,
                "bfe6" => EIntrinsic.Health,
                "c3a5" => EIntrinsic.LineSwitchSpeed,
                "eef8" => EIntrinsic.HidePerfromed,
                "e84e" => EIntrinsic.SlidePerfromed,
                "df05" => EIntrinsic.LineSwitched,
                "0519" => EIntrinsic.Height,
                _ => throw new ArgumentOutOfRangeException(nameof(guid4), guid4, "Unknown GUID for EIntrinsic.")
            };
        }
    }
}