// Auto-generated by StatAndIntrinsicEnumGenerator.cs on 6/2/2025 1:23:05 AM
// Based on IntrinsicSchemaObject assets found in StatSettings.
// Total items found: 14

using System;

namespace _src.Scripts.StatsHelpers.StatsHelpers.Data
{
    public enum EIntrinsic : byte
    {
        NullIntrinsic = 0, // From: Null Intrinsic, GUID Prefix: 5852
        MetroCoin = 1, // From: 1 Metro Coin, GUID Prefix: 4da0
        XP = 2, // From: 2 XP, GUID Prefix: b0f6
        Level = 3, // From: 3 Level, GUID Prefix: a3b2
        DistanceRun = 4, // From: 4 Distance Run, GUID Prefix: f7bd
        MissionsComplete = 5, // From: 5 Missions Complete, GUID Prefix: ef98
        JumpsPerformed = 6, // From: 6 Jumps Performed, GUID Prefix: cb70
        SlidesPerformed = 7, // From: 7 Slides Performed, GUID Prefix: 8db4
        NearMisses = 8, // From: 8 Near Misses, GUID Prefix: 3686
        PowerupsCollected = 9, // From: 9 Powerups Collected, GUID Prefix: 20b2
        CurrentThreat = 10, // From: 10 Current Threat, GUID Prefix: 5320
        RunTimer = 11, // From: 11 Run Timer, GUID Prefix: a5ef
        ParkourCount = 12, // From: 12 Parkour Count, GUID Prefix: d396
        Money = 13, // From: 13 Money, GUID Prefix: 848e
    }

    public static class EIntrinsicExt
    {
        public static string GetGuid(this EIntrinsic item)
        {
            return item switch
            {
                EIntrinsic.NullIntrinsic => "5852",
                EIntrinsic.MetroCoin => "4da0",
                EIntrinsic.XP => "b0f6",
                EIntrinsic.Level => "a3b2",
                EIntrinsic.DistanceRun => "f7bd",
                EIntrinsic.MissionsComplete => "ef98",
                EIntrinsic.JumpsPerformed => "cb70",
                EIntrinsic.SlidesPerformed => "8db4",
                EIntrinsic.NearMisses => "3686",
                EIntrinsic.PowerupsCollected => "20b2",
                EIntrinsic.CurrentThreat => "5320",
                EIntrinsic.RunTimer => "a5ef",
                EIntrinsic.ParkourCount => "d396",
                EIntrinsic.Money => "848e",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, "Unknown EIntrinsic value for GetGuid.")
            };
        }

        public static string ToName(this EIntrinsic item)
        {
            return item switch
            {
                EIntrinsic.NullIntrinsic => "Null Intrinsic",
                EIntrinsic.MetroCoin => "Metro Coin",
                EIntrinsic.XP => "XP",
                EIntrinsic.Level => "Level",
                EIntrinsic.DistanceRun => "Distance Run",
                EIntrinsic.MissionsComplete => "Missions Complete",
                EIntrinsic.JumpsPerformed => "Jumps Performed",
                EIntrinsic.SlidesPerformed => "Slides Performed",
                EIntrinsic.NearMisses => "Near Misses",
                EIntrinsic.PowerupsCollected => "Powerups Collected",
                EIntrinsic.CurrentThreat => "Current Threat",
                EIntrinsic.RunTimer => "Run Timer",
                EIntrinsic.ParkourCount => "Parkour Count",
                EIntrinsic.Money => "Money",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, "Unknown EIntrinsic value for ToName.")
            };
        }

        public static EIntrinsic FromGuid(string guid4)
        {
            if (guid4 == null || guid4.Length != 4)
            {
                throw new ArgumentException($"GUID must be 4 characters long.", nameof(guid4));
            }

            return guid4 switch
            {
                "5852" => EIntrinsic.NullIntrinsic,
                "4da0" => EIntrinsic.MetroCoin,
                "b0f6" => EIntrinsic.XP,
                "a3b2" => EIntrinsic.Level,
                "f7bd" => EIntrinsic.DistanceRun,
                "ef98" => EIntrinsic.MissionsComplete,
                "cb70" => EIntrinsic.JumpsPerformed,
                "8db4" => EIntrinsic.SlidesPerformed,
                "3686" => EIntrinsic.NearMisses,
                "20b2" => EIntrinsic.PowerupsCollected,
                "5320" => EIntrinsic.CurrentThreat,
                "a5ef" => EIntrinsic.RunTimer,
                "d396" => EIntrinsic.ParkourCount,
                "848e" => EIntrinsic.Money,
                _ => throw new ArgumentOutOfRangeException(nameof(guid4), guid4, "Unknown GUID for EIntrinsic.")
            };
        }
    }
}