// Auto-generated by StatAndIntrinsicEnumGenerator.cs on 6/11/2025 9:57:54 AM
// Based on StatSchemaObject assets found in StatSettings.
// Total items found: 6

using System;

namespace _src.Scripts.StatsHelpers.StatsHelpers.Data
{
    public enum EStat : ushort
    {
        NullStat = 0, // From: Null Stat, GUID Prefix: f2a5
        MaxForwardSpeed = 1, // From: 1 Max Forward Speed, GUID Prefix: 594b
        MaxSwitchSpeed = 2, // From: 2 Max Switch Speed, GUID Prefix: 4fe3
        MaxStrength = 3, // From: 3 Max Strength, GUID Prefix: 52f4
        MaxHealth = 4, // From: 4 Max Health, GUID Prefix: be91
        MaxJumpForce = 5, // From: 5 Max JumpForce, GUID Prefix: f15b
    }

    public static class EStatExt
    {
        public static string GetGuid(this EStat item)
        {
            return item switch
            {
                EStat.NullStat => "f2a5",
                EStat.MaxForwardSpeed => "594b",
                EStat.MaxSwitchSpeed => "4fe3",
                EStat.MaxStrength => "52f4",
                EStat.MaxHealth => "be91",
                EStat.MaxJumpForce => "f15b",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, "Unknown EStat value for GetGuid.")
            };
        }

        public static string ToName(this EStat item)
        {
            return item switch
            {
                EStat.NullStat => "Null Stat",
                EStat.MaxForwardSpeed => "Max Forward Speed",
                EStat.MaxSwitchSpeed => "Max Switch Speed",
                EStat.MaxStrength => "Max Strength",
                EStat.MaxHealth => "Max Health",
                EStat.MaxJumpForce => "Max JumpForce",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, "Unknown EStat value for ToName.")
            };
        }

        public static EStat FromGuid(string guid4)
        {
            if (guid4 == null || guid4.Length != 4)
            {
                throw new ArgumentException($"GUID must be 4 characters long.", nameof(guid4));
            }

            return guid4 switch
            {
                "f2a5" => EStat.NullStat,
                "594b" => EStat.MaxForwardSpeed,
                "4fe3" => EStat.MaxSwitchSpeed,
                "52f4" => EStat.MaxStrength,
                "be91" => EStat.MaxHealth,
                "f15b" => EStat.MaxJumpForce,
                _ => throw new ArgumentOutOfRangeException(nameof(guid4), guid4, "Unknown GUID for EStat.")
            };
        }
    }
}