// Auto-generated by StatAndIntrinsicEnumGenerator.cs on 6/6/2025 6:22:51 AM
// Based on StatSchemaObject assets found in StatSettings.
// Total items found: 6

using System;

namespace _src.Scripts.StatsHelpers.StatsHelpers.Data
{
    public enum EStat : ushort
    {
        NullStat = 0, // From: Null Stat, GUID Prefix: f2a5
        ForwardSpeed = 1, // From: 1 Forward Speed, GUID Prefix: 594b
        SwitchSpeed = 2, // From: 2 Switch Speed, GUID Prefix: 4fe3
        Strength = 3, // From: 3 Strength, GUID Prefix: 52f4
        MaxHealth = 4, // From: 4 Max Health, GUID Prefix: be91
        JumpForce = 5, // From: 5 JumpForce, GUID Prefix: f15b
    }

    public static class EStatExt
    {
        public static string GetGuid(this EStat item)
        {
            return item switch
            {
                EStat.NullStat => "f2a5",
                EStat.ForwardSpeed => "594b",
                EStat.SwitchSpeed => "4fe3",
                EStat.Strength => "52f4",
                EStat.MaxHealth => "be91",
                EStat.JumpForce => "f15b",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, "Unknown EStat value for GetGuid.")
            };
        }

        public static string ToName(this EStat item)
        {
            return item switch
            {
                EStat.NullStat => "Null Stat",
                EStat.ForwardSpeed => "Forward Speed",
                EStat.SwitchSpeed => "Switch Speed",
                EStat.Strength => "Strength",
                EStat.MaxHealth => "Max Health",
                EStat.JumpForce => "JumpForce",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, "Unknown EStat value for ToName.")
            };
        }

        public static EStat FromGuid(string guid4)
        {
            if (guid4 == null || guid4.Length != 4)
            {
                throw new ArgumentException($"GUID must be 4 characters long.", nameof(guid4));
            }

            return guid4 switch
            {
                "f2a5" => EStat.NullStat,
                "594b" => EStat.ForwardSpeed,
                "4fe3" => EStat.SwitchSpeed,
                "52f4" => EStat.Strength,
                "be91" => EStat.MaxHealth,
                "f15b" => EStat.JumpForce,
                _ => throw new ArgumentOutOfRangeException(nameof(guid4), guid4, "Unknown GUID for EStat.")
            };
        }
    }
}